version: '3'

networks:
    mysql-security-network:
        driver: bridge

services:
    mysql-server:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: Security1234567890!
            MYSQL_DATABASE: security
            MYSQL_USER: db_username
            MYSQL_PASSWORD: db_password
        networks:
            - mysql-security-network

    phpmyadmin:
        depends_on:
            - mysql-server
        image: phpmyadmin:latest
        ports:
            - '8081:80'
        environment:
            PMA_HOST: mysql-server
        networks:
            - mysql-security-network

    laravel-app:
        build:
            context: .
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql-server
            DB_PORT: 3306
            DB_DATABASE: security
            DB_USERNAME: db_username
            DB_PASSWORD: db_password
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql-server
        networks:
            - mysql-security-network

    webserver:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel-app
        networks:
            - mysql-security-network
